# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-SAPI5
version:      0.02
version_from: lib/Win32/SAPI5.pm
installdirs:  site
requires:
    Win32::OLE:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
